/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Editor Animations",
  "description": "Adds smooth animations to various aspects of the editor!",
  "credits": [
    {
      "name": "reflow"
    },
    {
      "name": "SharkPool"
    }
  ],
  "info": [
    {
      "type": "notice",
      "text": "This addon will not take effect if you have animations turned off on your system. See https://mgik.dev/turn-on-motion for how to turn it on.",
      "id": "reduced-motion-notice"
    }
  ],
  "settings": [
    {
      "id": "animateButtons",
      "name": "Animate Buttons",
      "default": true,
      "dynamic": true,
      "type": "boolean"
    },
    {
      "id": "animateLibraries",
      "name": "Animate Libraries (costumes, sprites, sounds, etc)",
      "default": true,
      "dynamic": true,
      "type": "boolean"
    },
    {
      "id": "animateModals",
      "name": "Animate Modals (create variable/list, custom block, etc)",
      "default": true,
      "dynamic": true,
      "type": "boolean"
    },
    {
      "id": "animateSpeed",
      "name": "Animation Speed (1-500%)",
      "type": "integer",
      "dynamic": true,
      "min": 1,
      "default": 100,
      "max": 500
    },
    {
      "id": "animationType",
      "name": "Animation Type",
      "type": "select",
      "dynamic": true,
      "default": "default",
      "potentialValues": [
        { "id": "default", "name": "Default" },
        { "id": "easeIn", "name": "Ease In" },
        { "id": "easeOut", "name": "Ease Out" },
        { "id": "easeInOut", "name": "Ease In Out" },
        { "id": "smoothStep", "name": "Smooth Step" },
        { "id": "fastInSlowOut", "name": "Fast In Slow Out" },
        { "id": "sineIn", "name": "Sine In" },
        { "id": "sineOut", "name": "Sine Out" },
        { "id": "sineInOut", "name": "Sine In Out" },
        { "id": "quadIn", "name": "Quadratic In" },
        { "id": "quadOut", "name": "Quadratic Out" },
        { "id": "quadInOut", "name": "Quadratic In Out" },
        { "id": "cubicIn", "name": "Cubic In" },
        { "id": "cubicOut", "name": "Cubic Out" },
        { "id": "cubicInOut", "name": "Cubic In Out" },
        { "id": "quartIn", "name": "Quartic In" },
        { "id": "quartOut", "name": "Quartic Out" },
        { "id": "quartInOut", "name": "Quartic In Out" },
        { "id": "quintIn", "name": "Quintic In" },
        { "id": "quintOut", "name": "Quintic Out" },
        { "id": "quintInOut", "name": "Quintic In Out" }
      ]
    },
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new", "theme"
  ],
  "enabledByDefault": true
};
export default manifest;
