/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Code Editor Tabbing",
  "description": "Adds tabs to the code editor, allowing you to devide many scripts from inside one sprite in to seperate parts.",
  "info": [],
  "credits": [
    {
      "name": "RedMan13",
      "link": "https://github.com/RedMan13"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "settings": [
    {
      "type": "boolean",
      "id": "shouldDelete",
      "name": "Merge tabs on delete",
      "default": "true",
      "description": "If we should keep blocks from deleted tabs, moving them into the new selected tab, or if we should delete blocks inside a deleted tab."
    }
  ],
  "tags": ["new"],
  "enabledByDefault": false
};
export default manifest;
