/* generated by pull.js */
export default async function ({ addon, console }) {
    let mouseX = 0;
    let mouseY = 0;
    let isMoving = false;

    // Track mouse position
    document.addEventListener('mousemove', (e) => {
        mouseX = e.clientX;
        mouseY = e.clientY;
        isMoving = true;
    });

    // Base64 SVGs of the Scratch icons
    const images = {
        green_flag: 'url(\'data:image/svg+xml;utf8,<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M6 2L6 22M6 2L20 8L6 14" stroke="green" stroke-width="2" fill="lime"/></svg>\')',
        stop_sign: 'url(\'data:image/svg+xml;utf8,<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><polygon points="8,2 16,2 22,8 22,16 16,22 8,22 2,16 2,8" fill="red" stroke="darkred" stroke-width="2"/></svg>\')',
        pause: 'url(\'data:image/svg+xml;utf8,<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><rect x="6" y="4" width="4" height="16" fill="gold"/><rect x="14" y="4" width="4" height="16" fill="gold"/></svg>\')'
    };

    const keys = ['green_flag', 'stop_sign', 'pause'];

    // Create particles on an interval, but only if the mouse actually moved
    setInterval(() => {
        if (!isMoving) return;
        isMoving = false;

        const particle = document.createElement('div');
        particle.className = 'tw-mouse-particle';

        // Center on the mouse pointer
        particle.style.left = (mouseX - 12) + 'px';
        particle.style.top = (mouseY - 12) + 'px';

        // Calculate random rotations
        const startRot = Math.random() * 360;
        // Spin random amount between 90 and 360 degrees, randomly clockwise/counter-clockwise
        const spinAmount = (Math.random() * 270 + 90) * (Math.random() > 0.5 ? 1 : -1); 
        const endRot = startRot + spinAmount;

        // Apply to CSS variables
        particle.style.setProperty('--start-rot', startRot + 'deg');
        particle.style.setProperty('--end-rot', endRot + 'deg');

        // Check settings for the current image
        let imgSetting = addon.settings.read('particle_image');
        if (imgSetting === 'random' || !images[imgSetting]) {
            imgSetting = keys[Math.floor(Math.random() * keys.length)];
        }

        particle.style.backgroundImage = images[imgSetting];

        document.body.appendChild(particle);

        // Delete the element after 1 second (matching the CSS animation time)
        setTimeout(() => {
            particle.remove();
        }, 1000);

    }, 40); // 40ms interval = ~25 particles per second
}